### ISSUE TITLE
Unable to send funds from Wallets(Petra)

### ISSUE THREAD

**Issue by andyjsbell** [movementlabsxyz/movement#164]
**Describe the bug**
Using accounts that have been funded we are unable to send funds form wallet UI to other accounts on the suzuka testnetwork.

**To Reproduce**

1. Add Suzuka Testnet to Petra Wallet
2. Fund from Faucet
3. Attempt to send funds to another wallet but unable to do so
5. Expected behavior
6. Funded wallet should be able to send Move to another wallet

![image](https://github.com/movementlabsxyz/movement/assets/39520002/392a586b-43d7-4dca-bc57-dd7fb6b82faf)

**Comment by andyjsbell** [comment]
It seems Razor Wallet is also running into similar issues see screenshot below after funding the account it is unable to send funds to any other wallet or do any basica transaction similar to Petra

![image](https://github.com/movementlabsxyz/movement/assets/39520002/c7790210-913c-49ea-9450-cf9f2ecd65a0)

**Comment by Rahat-ch** [comment]
Additional information from nightly team having same issue 

<img width="521" alt="Screen Shot 2024-07-04 at 10 27 07 AM" src="https://github.com/movementlabsxyz/movement/assets/40510125/f512304f-e897-4f4a-a864-83a145a98ffa">

**Comment by 0xPrimata** [comment]
Razor is fine sending to an initialized or uninitialized wallet
![Screenshot 2024-07-11 at 6 50 56 PM](https://github.com/user-attachments/assets/4b0df857-2d88-4d06-88bf-fc032b800535)
Petra transaction simulation errors on the same issue present on a persistent issue across the board. This error is produced whenever a request is made to the GraphQL Indexer, it doesn't receive a response and is unable to loop through the response object because the object is Not Found.
![image](https://github.com/user-attachments/assets/f2d5d7f6-08cd-4312-b21c-eade41b4d5f6)

Should be solved by https://github.com/movementlabsxyz/movement/tree/l-monninger/indexer-integration

**Comment by andyjsbell** [comment]
@0xPrimata @Rahat-ch the indexer will be included shortly but I don't think this will fix the issue.  The indexer as it has been termed is the raw gRPC stream of transactions that are consumed by the Transaction Stream Service which is in turn consumed by the Indexer API which finally exposes the expected GraphQL API.  Once we have the referenced PR merged and deployed infrastructure for the TSS and Indexer API would be needed.  We have plans to have this infrastructure in place within the next two weeks.
